### ISSUE TITLE
RejectedExecutionException happening on CRUD servers

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-rest#106]
The below exception is repeatedly showing up in the logs of our CRUD servers.

Found this article that might help:
http://examples.javacodegeeks.com/core-java/util/concurrent/rejectedexecutionexception/java-util-concurrent-rejectedexecutionexception-how-to-solve-rejectedexecutionexception/

```
2015-03-02 12:24:58,996 [https_executor-threads - 85] ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/rest/data].[com.redhat.lightblue.rest.crud.RestApplication]] JBWEB000236: Servlet.service() for servlet com.redhat.lightblue.rest.crud.RestApplication threw exception: org.jboss.resteasy.spi.UnhandledException: com.netflix.hystrix.exception.HystrixRuntimeException: FindCommand could not be queued for execution and no fallback available.
	at org.jboss.resteasy.core.SynchronousDispatcher.handleApplicationException(SynchronousDispatcher.java:365)
	at org.jboss.resteasy.core.SynchronousDispatcher.handleException(SynchronousDispatcher.java:233)
	at org.jboss.resteasy.core.SynchronousDispatcher.handleInvokerException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:557)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:126)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:508)
	at org.jboss.threads.SimpleDirectExecutor.execute(SimpleDirectExecutor.java:33)
	at org.jboss.threads.QueueExecutor.runTask(QueueExecutor.java:806)
	at org.jboss.threads.QueueExecutor.access$100(QueueExecutor.java:45)
	at org.jboss.threads.QueueExecutor$Worker.run(QueueExecutor.java:847)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: FindCommand could not be queued for execution and no fallback available.
	at com.netflix.hystrix.HystrixObservableCommand$15.call(HystrixObservableCommand.java:689)
	at com.netflix.hystrix.HystrixObservableCommand$15.call(HystrixObservableCommand.java:672)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:76)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:48)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.Observable$ThrowObservable$1.call(Observable.java:10489)
	at rx.Observable$ThrowObservable$1.call(Observable.java:10479)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:48)
	at com.netflix.hystrix.HystrixCommand$HystrixCommandFromObservableCommand$2.call(HystrixCommand.java:375)
	at com.netflix.hystrix.HystrixCommand$HystrixCommandFromObservableCommand$2.call(HystrixCommand.java:367)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:48)
	at com.netflix.hystrix.HystrixObservableCommand$HystrixObservableTimeoutOperator$3.onError(HystrixObservableCommand.java:858)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.Observable$2.call(Observable.java:181)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at com.netflix.hystrix.HystrixObservableCommand$1.call(HystrixObservableCommand.java:295)
	at com.netflix.hystrix.HystrixObservableCommand$1.call(HystrixObservableCommand.java:273)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at com.netflix.hystrix.HystrixExecutableBase$ObservableCommand$1.call(HystrixExecutableBase.java:652)
	at com.netflix.hystrix.HystrixExecutableBase$ObservableCommand$1.call(HystrixExecutableBase.java:648)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable.subscribe(Observable.java:8676)
	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:55)
	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:420)
	at com.netflix.hystrix.HystrixExecutableBase.queue(HystrixExecutableBase.java:342)
	at com.netflix.hystrix.HystrixObservableCommand.queue(HystrixObservableCommand.java:50)
	at com.netflix.hystrix.HystrixExecutableBase.execute(HystrixExecutableBase.java:296)
	at com.netflix.hystrix.HystrixObservableCommand.execute(HystrixObservableCommand.java:50)
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:485)
	at com.redhat.lightblue.rest.crud.AbstractCrudResource.find(AbstractCrudResource.java:179)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:269)
	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:227)
	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:542)
	... 25 more
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7486c091 rejected from java.util.concurrent.ThreadPoolExecutor@4260f924[Running, pool size = 10, active threads = 10, queued tasks = 0, completed tasks = 89]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:110)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextScheduler$ThreadPoolWorker.schedule(HystrixContextScheduler.java:157)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextScheduler$HystrixContextSchedulerWorker.schedule(HystrixContextScheduler.java:101)
	at rx.internal.operators.OperatorSubscribeOn$1.onNext(OperatorSubscribeOn.java:57)
	at rx.internal.operators.OperatorSubscribeOn$1.onNext(OperatorSubscribeOn.java:43)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:41)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:30)
	at rx.Observable$2.call(Observable.java:173)
	... 69 more
```

**Comment by dcrissman** [comment]
Wiki that details the hystrix configuration. I am focusing on maxQueueSize and queueSizeRejectionThreshold.
https://github.com/Netflix/Hystrix/wiki/Configuration

**Comment by dcrissman** [comment]
Hystrix is currently being configured via puppet. See lightblue::eap::module and config.properties.erb.

**Comment by dcrissman** [comment]
If the migrator has more than X records from the source, then send requests to the destination in batches.
https://github.com/lightblue-platform/lightblue-migrator/pull/77

**Comment by dcrissman** [comment]
Added the following settings to /usr/share/jbossas/modules/com/redhat/lightblue/main/config.properties

```
hystrix.command.default.maxQueueSize=40
hystrix.command.default.queueSizeRejectionThreshold=40
```

**Comment by dcrissman** [comment]
I have made changes to the migrator to batch certain types of operations and that seems to be helping. At this time I will go ahead and close this ticket out as it now seems to be more of an issue on the migrator side.
