### ISSUE TITLE
Hystrix timeouts

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-rest#142]
We started to get the below exception on Friday April 24th at around 9AM. The only snapshot build for that day was based off git hash 32d58f16965854d0455ccaecd35f84750a336fea. Which was for https://github.com/lightblue-platform/lightblue-rest/pull/128. We need to investigate to see what is going on.

```
015-04-29 09:52:45,244 [https_executor-threads - 383] ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/rest/data].[com.redhat.lightblue.rest.crud.RestApplication]] JBWEB000236: Servlet.service() for servlet com.redhat.lightblue.rest.crud.RestApplication threw exception: org.jboss.resteasy.spi.UnhandledException: com.netflix.hystrix.exception.HystrixRuntimeException: FindCommand timed-out and no fallback available.
	at org.jboss.resteasy.core.SynchronousDispatcher.handleApplicationException(SynchronousDispatcher.java:365)
	at org.jboss.resteasy.core.SynchronousDispatcher.handleException(SynchronousDispatcher.java:233)
	at org.jboss.resteasy.core.SynchronousDispatcher.handleInvokerException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:557)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:126)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at com.redhat.lightblue.rest.audit.LightblueAuditServletFilter.doFilter(LightblueAuditServletFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:438)
	at org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:508)
	at org.jboss.threads.SimpleDirectExecutor.execute(SimpleDirectExecutor.java:33)
	at org.jboss.threads.QueueExecutor.runTask(QueueExecutor.java:806)
	at org.jboss.threads.QueueExecutor.access$100(QueueExecutor.java:45)
	at org.jboss.threads.QueueExecutor$Worker.run(QueueExecutor.java:847)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: FindCommand timed-out and no fallback available.
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:760)
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:747)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1388)
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1278)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:314)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:306)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:78)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.run(AbstractCommand.java:867)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:37)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:57)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$2.tick(AbstractCommand.java:887)
	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException
	at com.netflix.hystrix.AbstractCommand$8.call(AbstractCommand.java:581)
	at com.netflix.hystrix.AbstractCommand$8.call(AbstractCommand.java:562)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	... 15 more
```

**Comment by dcrissman** [comment]
I believe this has to do with a slow down in parsing the request using so many regexes. I am working on a change that will at least do this asynchronously as to not affect the response time.

**Comment by luan-cestari** [comment]
I dont think regex would impact that much, but surely it adds an overhead of the URL processing (as that even the JAX-RS impl will do that). Audit log have many exclusive conditions which would not make it just a small set of regex to be executed and the pattern is already generated, so I would not expect it to take so much time. It would be nice if we profile the execution after all the variables are initialized and the JIT turned most of the code to native (also remove other biases)

**Comment by dcrissman** [comment]
I am no longer seeing this exception, closing.
