### ISSUE TITLE
Getting error while deploying lightblue on WildFly 10.1.0

### ISSUE THREAD

**Issue by JankiGadhiya** [lightblue-platform/lightblue-rest#246]
This is the error i am getting : 
```

10:34:15,886 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-4) MSC000001: Failed to start service jboss.module.service."deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war".main: org.jboss.msc.service.StartException in service jboss.module.service."deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war".main: WFLYSRV0179: Failed to load module: deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war:main
	at org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:91)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.modules.ModuleNotFoundException: com.redhat.lightblue:main
	at org.jboss.modules.Module.addPaths(Module.java:1093)
	at org.jboss.modules.Module.link(Module.java:1449)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1477)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:225)
	at org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:68)
	... 5 more

10:34:15,888 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 64) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war")]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.module.service.\"deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\".main: WFLYSRV0179: Failed to load module: deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war:main
    Caused by: org.jboss.modules.ModuleNotFoundException: com.redhat.lightblue:main"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.module.service.\"deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\".main"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
10:34:15,888 ERROR [org.jboss.as.server] (management-handler-thread - 64) WFLYSRV0021: Deploy of deployment "lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war" was rolled back with the following failure message: 
{
    "WFLYCTL0080: Failed services" => {"jboss.module.service.\"deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\".main" => "org.jboss.msc.service.StartException in service jboss.module.service.\"deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\".main: WFLYSRV0179: Failed to load module: deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war:main
    Caused by: org.jboss.modules.ModuleNotFoundException: com.redhat.lightblue:main"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.module.service.\"deployment.lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\".main"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
```

I have found some solutions that are telling me to add `module.xml` but I don't know exactly where to add that and what should be the content of `module.xml` for light blue.

I am very new in wildfly deployment it will great help if anyone comes up with a solution.

Anyone with the same error as mine ?

**Comment by bserdar** [comment]
You need to add a directory  $JBOSS_HOME/modules/com/redhat/lightblue/main, and put the configuration files there. There are examples here: https://github.com/lightblue-platform/lightblue-rest/tree/master/etc/jbossas/modules/com/redhat/lightblue/main

**Comment by JankiGadhiya** [comment]
Thanx @bserdar. I have done as you said and thank you that error is gone.

But there is another error can you please look into this : 

```
11:31:35,426 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-5) MSC000001: Failed to start service jboss.deployment.unit."lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.unit."lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war".INSTALL: WFLYSRV0153: Failed to process phase INSTALL of deployment "lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.msc.service.DuplicateServiceException: Service jboss.undertow.deployment.default-server.default-host./rest/data.session is already registered
	at org.jboss.msc.service.ServiceRegistrationImpl.setInstance(ServiceRegistrationImpl.java:158)
	at org.jboss.msc.service.ServiceControllerImpl.startInstallation(ServiceControllerImpl.java:235)
	at org.jboss.msc.service.ServiceContainerImpl.install(ServiceContainerImpl.java:768)
	at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223)
	at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2401)
	at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223)
	at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2401)
	at org.jboss.msc.service.ServiceBuilderImpl.install(ServiceBuilderImpl.java:317)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentProcessor.installSessionManagerFactory(UndertowDeploymentProcessor.java:421)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentProcessor.processDeployment(UndertowDeploymentProcessor.java:338)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentProcessor.deploy(UndertowDeploymentProcessor.java:133)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	... 5 more

11:31:35,433 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 8) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\".INSTALL" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\".INSTALL: WFLYSRV0153: Failed to process phase INSTALL of deployment \"lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\"
    Caused by: org.jboss.msc.service.DuplicateServiceException: Service jboss.undertow.deployment.default-server.default-host./rest/data.session is already registered"}}
11:31:35,437 ERROR [org.jboss.as.server] (management-handler-thread - 8) WFLYSRV0021: Deploy of deployment "lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\".INSTALL" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\".INSTALL: WFLYSRV0153: Failed to process phase INSTALL of deployment \"lightblue-rest-crud-basic-auth-2.10.0-SNAPSHOT.war\"
    Caused by: org.jboss.msc.service.DuplicateServiceException: Service jboss.undertow.deployment.default-server.default-host./rest/data.session is already registered"}}
```

**Comment by bserdar** [comment]
org.jboss.msc.service.DuplicateServiceException: you seem to have the same service more than once.

For no authentication setup, simply deploy the wars under metadata and crud.  crud-basic-auth and crud-cert-auth are different authentication variants of the same service. Same for metadata.

**Comment by JankiGadhiya** [comment]
@bserdar Thanks for everything. Can you please help me in one more thing ??

I am not able to access the light blue rest services by : http://localhost:8080/lightblue-rest-metadata/

I am getting **404 - Not found error** how can i access the rest service can you please tell me??

**Comment by bserdar** [comment]
Try /rest/metadata
Check the specs document for the rest spec

**Comment by JankiGadhiya** [comment]
@bserdar Hi, http://localhost:8080/rest/metadata/ is giving **Forbidden**.

Can you please guide me in this??

**Comment by bserdar** [comment]
Did you deploy one of the auth versions? Deploy either metadata or crud
WARs (without auth).

Answers to all these can be found in the docs:

https://github.com/lightblue-platform/lightblue-docs-user
https://github.com/lightblue-platform/lightblue-docs-developer
https://github.com/lightblue-platform/lightblue-docs-specs

**Comment by JankiGadhiya** [comment]
Thank you so much for your help @bserdar.
Now I am able to access the rest APIs successfully for metadata & CRUD operations.
